# Generated by Django 5.0.6 on 2025-01-21 15:26

import uuid
from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    Business = apps.get_model('products', 'Business')
    Product = apps.get_model('products', 'Product')
    for b in Business.objects.all():
        if not getattr(b, 'uuid_id', None):
            b.uuid_id = uuid.uuid4()
            b.save(update_fields=['uuid_id'])
    for p in Product.objects.all():
        if not getattr(p, 'uuid_id', None):
            p.uuid_id = uuid.uuid4()
            p.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_business_business_image_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_business ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_business_uuid_id_idx ON products_business(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_product ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_product_uuid_id_idx ON products_product(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(gen_uuids, migrations.RunPython.noop),
    ]
