# Generated by Django 5.0.6 on 2025-03-20 10:30

import uuid
from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    for model_name in ('Notification', 'Order', 'Review', 'Wishlist', 'Sales'):
        try:
            Model = apps.get_model('products', model_name)
        except LookupError:
            continue
        for obj in Model.objects.all():
            if not getattr(obj, 'uuid_id', None):
                obj.uuid_id = uuid.uuid4()
                obj.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.RunPython(gen_uuids, migrations.RunPython.noop),
    ]
