# Generated by Django 5.0.6 on 2025-03-20 10:30

import uuid
from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    for model_name in ('Notification', 'Order', 'Review', 'Wishlist', 'Sales'):
        try:
            Model = apps.get_model('products', model_name)
        except LookupError:
            continue
        for obj in Model.objects.all():
            if not getattr(obj, 'uuid_id', None):
                obj.uuid_id = uuid.uuid4()
                obj.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_review_unique_together'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_notification ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_notification_uuid_id_idx ON products_notification(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_order ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_order_uuid_id_idx ON products_order(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_review ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_review_uuid_id_idx ON products_review(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_sales ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_sales_uuid_id_idx ON products_sales(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE IF EXISTS products_wishlist ADD COLUMN IF NOT EXISTS uuid_id uuid;"
                "CREATE UNIQUE INDEX IF NOT EXISTS products_wishlist_uuid_id_idx ON products_wishlist(uuid_id);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(gen_uuids, migrations.RunPython.noop),
    ]
