# Generated by Django 5.0.6 on 2025-03-30 23:24

import uuid
from django.db import migrations, models


def gen_order_uuid(apps, schema_editor):
    try:
        Order = apps.get_model('products', 'Order')
    except LookupError:
        return
    for o in Order.objects.all():
        if not getattr(o, 'uuid_id', None):
            o.uuid_id = uuid.uuid4()
            o.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.RunPython(gen_order_uuid, migrations.RunPython.noop),
    ]
