# Generated by Django 5.0.6 on 2026-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_business_business_description'),
    ]

    operations = [
        # Use idempotent SQL so repeated runs don't fail on DuplicateColumn
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_business ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_business_uuid_id_idx ON products_business(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_category ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_category_uuid_id_idx ON products_category(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_notification ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_notification_uuid_id_idx ON products_notification(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_order ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_order_uuid_id_idx ON products_order(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_product_uuid_id_idx ON products_product(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_review ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_review_uuid_id_idx ON products_review(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_sellerreport ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_sellerreport_uuid_id_idx ON products_sellerreport(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_wishlist ADD COLUMN IF NOT EXISTS uuid_id uuid UNIQUE NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS products_wishlist_uuid_id_idx ON products_wishlist(uuid_id) WHERE uuid_id IS NOT NULL;
            """,
            reverse_sql=None,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
