# Generated by Django 5.0.6 on 2026-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_business_business_description'),
    ]

    operations = [
        # Use idempotent SQL so repeated runs don't fail on DuplicateColumn
        migrations.AddField(
            model_name='business',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellerreport',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        # Skip AlterField for category.id — if id is already uuid, don't attempt to cast back to bigint
        # This is a no-op to preserve the existing schema state
        migrations.RunSQL(
            sql="SELECT 1;",  # no-op
            reverse_sql=None,
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
