# Generated by Django 5.0.6 on 2026-01-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_business_uuid_id_category_uuid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        # Skip altering `category.id` back to BigAutoField — unsafe when IDs are UUIDs.
        # This no-op preserves the current schema and avoids Postgres cast errors.
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerreport',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='uuid_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
