# Generated by Django 5.0.6 on 2026-01-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_business_uuid_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_category.png', upload_to='product_category/'),
        ),
    ]
