# Generated by Django 5.0.6 on 2025-01-21 15:26
# MODIFIED: Safe UUID migration that doesn't try to cast bigint -> uuid
# This creates a new uuid column, backfills it, then swaps it as the PK.

import uuid
from django.db import migrations, models


def add_uuid_ids(apps, schema_editor):
    """Backfill UUID values for existing rows."""
    Message = apps.get_model('chat', 'Message')
    for msg in Message.objects.all():
        if not msg.uuid_id:
            msg.uuid_id = uuid.uuid4()
            msg.save()
    
    Profile = apps.get_model('chat', 'Profile')
    for prof in Profile.objects.all():
        if not prof.uuid_id:
            prof.uuid_id = uuid.uuid4()
            prof.save()


def reverse_uuid_ids(apps, schema_editor):
    """Reverse: clear the UUID column."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        # Step 1: Add uuid_id column (nullable) for both Message and Profile
        migrations.AddField(
            model_name='message',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        # Step 2: Backfill UUID values for existing rows
        migrations.RunPython(add_uuid_ids, reverse_uuid_ids),
        # Step 3: Make uuid_id NOT NULL
        migrations.AlterField(
            model_name='message',
            name='uuid_id',
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid_id',
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False),
        ),
    ]
