# Generated by Django 5.0.6 on 2026-01-02 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_customuser_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
