# Generated by Django 5.0.6 on 2026-01-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_message_uuid_id_alter_profile_uuid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='default_profile.png', upload_to='user_profiles'),
        ),
    ]
